#!/bin/bash
 > temp.txt
 > date.txt
 > rooms.txt
 > valeurs.txt
 > moyenne.txt
 > valeur101.txt
 > valeur102.txt
 > moyenne1.txt
 > moyenne2.txt
 > extremp.txt
 > extremp1.txt
 > extremp2.txt
 > extremm.txt
 > extremm1.txt
 > extremm2.txt
let min=max=min1=min2=max1=max2=0
while true; do
 mosquitto_sub -C 1 -h iot.iut-blagnac.fr -u student -P student -t iut/bate/etage1/+/luminosite >> temp.txt
 lignes=`wc -l < temp.txt | cut -d ' ' -f 1`
 date +%x-%X >> date.txt
 tail -1 temp.txt | cut -d '"' -f 4 >> rooms.txt
 tail -1 temp.txt | cut -d ':' -f 3 | sed 's/}//' >> valeurs.txt

 vfin=`tail -1 valeurs.txt`
 nbr_total=`wc -l < temp.txt | cut -d ' ' -f 1 `
 let somme=$somme+$vfin
 echo $vfin
 if [ $max == 0 ] || [ $min == 0 ];then
  max=$vfin
  min=$vfin
  record=`date +%x-%X`
  echo "Maximum historique atteint pour la valeur de $max le $record." > extremp.txt
  echo "Minimum historique atteint pour la valeur de $min le $record." > extremm.txt
 fi
 if [ $vfin -gt $max ];then
  max=$vfin
  test=`cut -d " " -f 8 extremp.txt`
  if [ $max \> $test ];then
   record=`date +%x-%X`
   echo "Maximum historique atteint pour la valeur de $max le $record." > extremp.txt
  fi
 fi
 if [ $vfin -lt $min ];then
  min=$vfin
  test=`cut -d " " -f 8 extremm.txt`
  if [ $min \> $test ];then
   record=`date +%x-%X`
   echo "Minimum historique atteint pour la valeur de $min le $record." > extremm.txt
  fi
 fi
 testsalle=`tail -1 rooms.txt`
 if [ $testsalle  == 'E101' ];then
  tail -1 valeurs.txt >> valeur101.txt
  vfin1=`tail -1 valeur101.txt`
  nbr_total1=`wc -l < valeur101.txt | cut -d ' ' -f 1 `
  let somme1=$somme1+$vfin1
  echo "valeur e101 $vfin1"
  if [ $max1 == 0 ] || [ $min1 == 0 ];then
   max1=$vfin1
   min1=$vfin1
   record=`date +%x-%X`
   echo "Maximum historique atteint pour la valeur de $max1 le $record." > extremp1.txt
   echo "Minimum historique atteint pour la valeur de $min1 le $record." > extremm1.txt
  fi
  if [ $vfin1 -gt $max1 ];then
   max1=$vfin1
   test=`cut -d " " -f 8 extremp1.txt`
   if [ $max1 \> $test ];then
    record=`date +%x-%X`
    echo "Maximum historique atteint pour la valeur de $max1 le $record." > extremp1.txt
   fi
  fi
  if [ $vfin1 -lt $min1 ];then
   min1=$vfin1
   test=`cut -d " " -f 8 extremm1.txt`
   if [ $min1 \> $test ];then
    record=`date +%x-%X`
    echo "Minimum historique atteint pour la valeur de $min1 le $record." > extremm1.txt
   fi
  fi
  let moyenne1=$somme1/$nbr_total1
  echo "$moyenne1, $min1, $max1" >> moyenne1.txt

 else
  tail -1 valeurs.txt >> valeur102.txt
  vfin2=`tail -1 valeur102.txt`
  nbr_total2=`wc -l < valeur102.txt | cut -d ' ' -f 1 `
  let somme2=$somme2+$vfin2
  echo "valeur e102 $vfin2"
  if [ $max2 == 0 ] || [ $min2 == 0 ];then
   max2=$vfin2
   min2=$vfin2
   record=`date +%x-%X`
   echo "Maximum historique atteint pour la valeur de $max2 le $record." > extremp2.txt
   echo "Minimum historique atteint pour la valeur de $min2 le $record." > extremm2.txt
  fi
  if [ $vfin2 -gt $max2 ];then
   max2=$vfin2
   test=`cut -d " " -f 8 extremp2.txt`
   if [ $max2 \> $test ];then
    record=`date +%x-%X`
    echo "Maximum historique atteint pour la valeur de $max2 le $record." > extremp2.txt
   fi
  fi
  if [ $vfin2 -lt $min2 ];then
   min2=$vfin2
   test=`cut -d " " -f 8 extremm2.txt`
   if [ $min2 \> $test ];then
    record=`date +%x-%X`
    echo "Minimum historique atteint pour la valeur de $min2 le $record." > extremm2.txt
   fi
  fi
  let moyenne2=$somme2/$nbr_total2
  echo "$moyenne2, $min2, $max2" >> moyenne2.txt
 fi

 let moyenne=$somme/$nbr_total
 echo "La somme de toutes les valeurs est : $somme"
 echo "La moyenne de toutes les valeurs est : $moyenne"
 echo "Le minimum de toutes les valeurs est : $min"
 echo "Le maximums de toutes les valeurs est : $max"
 echo "$moyenne, $min, $max" >> moyenne.txt

 if [ $lignes -gt 20 ]; then
  cp temp.txt archive.txt
  cp date.txt datarchive.txt
  cp rooms.txt roomsarchive.txt
  cp valeurs.txt valeursarchive.txt
  cp moyenne.txt moyennearchive.txt
  > temp.txt
  > valeur101.txt
  > valeur102.txt
  > date.txt
  > rooms.txt
  > valeurs.txt
  > moyenne.txt
  > moyenne1.txt
  > moyenne2.txt
  > extremp.txt
  > extremp1.txt
  > extremp2.txt
  > extremm.txt
  > extremm1.txt
  > extremm2.txt
 fi
done
